### ISSUE TITLE
`NSRunningApplication` missing `processIdentifier` method

### ISSUE THREAD

**Issue by ok-nick** [madsmtm/objc2#542] opened 2023-12-22 19:37 UTC
Hi, the [`NSRunningApplication`](https://developer.apple.com/documentation/appkit/nsrunningapplication) class is missing the [`processIdentifier`](https://developer.apple.com/documentation/appkit/nsrunningapplication/1526998-processidentifier) method. I'm assuming it's something to do with the `pid_t` type causing this method to not be auto-generated?

For now I'm going to use `msg_send`, but if there's anything that can be done to fix this issue I'd be happy to send a PR.

Edit: Does this look correct?
```rust
unsafe fn NSRunningApplication_processIdentifier(
    app: &icrate::AppKit::NSRunningApplication,
) -> std::os::raw::c_int {
    unsafe { msg_send![app, processIdentifier] }
}
```

**Comment by madsmtm** [comment] 2023-12-22 19:52
Duplicate of https://github.com/madsmtm/objc2/issues/331, see that one for details on why we don't do `libc` types yet

**Closed by madsmtm** 2023-12-22 19:52 UTC
