### ISSUE TITLE
Add some examples/documentation for standard use cases (e..g, getting an ObjC struct into rust)

### ISSUE THREAD

**Issue by marcpabst** [madsmtm/objc2#582] opened 2024-02-11 14:59 UTC
I'm attempting to use `objc2` for Apple iOS API interoperability, and I'm really struggling with basic tasks, such as retrieving an Objective-C struct (simd_float4x4, [https://developer.apple.com/documentation/arkit/aranchor/2867981-transform?language=objc](https://developer.apple.com/documentation/arkit/aranchor/2867981-transform?language=objc)) from an object into Rust. Naively, I assumed this would work, but it doesn't:

```rust
#[repr(C)]
struct SimdFloat4x4 {
    columns: [SimdFloat4; 4],
}


#[repr(C)]
struct SimdFloat4 {
    x: f32,
    y: f32,
    z: f32,
    w: f32,
}
```
and then

```rust
let face_transform:  SimdFloat4x4 = unsafe { msg_send![anchor, transform] };
```

Could we have some more examples for things like this?

**Comment by madsmtm** [comment] 2024-02-12 02:11
Well, it does say in [the docs for `msg_send!`](https://docs.rs/objc2/0.5.0/objc2/macro.msg_send.html#specification):

> All arguments, as well as the return type, must implement `Encode`

And `SimdFloat4` doesn't, because you haven't implemented that trait.

But I definitely recognize that this is not visible, and there should be some more introductory-level docs for this!

**Comment by marcpabst** [comment] 2024-02-13 16:58
I think I was a bit tired and frustrated when writing this, my aplogies for that. I actually tried implementing `Encode`, but the code I copied in here is `objc` code which actually works. But as it turns out, `SimdFloat4` is super opaque and apple seems to do some funny things under the hood. I only managed to get the first column out, the rest is all gibbersih. Now using some ObjectiveC glue code (basically reading and creating an array from that on the Objective C side) it works.

But maybe worth keeping in mind when support for `simd` types is added!

**Comment by madsmtm** [comment] 2024-02-13 18:02
> I think I was a bit tired and frustrated when writing this, my aplogies for that

No problem, it didn't register as rude to me.

> I actually tried implementing `Encode`

Huh, yeah, I see what you mean, `Encoding` can't actually represent the encoding of SIMD types, as they don't actually have an encoding (`@encode(simd_float4) == ""` and `@encode(simd_float4x4) == "{?=[4]}"`, which our encoding routines can't handle).

This may actually a problem, because we use the encoding as part of figuring out the correct calling convention; but then again, a type like `typedef __attribute__((__ext_vector_type__(1))) long double simd_longdouble;` also breaks in Clang, so maybe it's not really an issue in practice.

I'll reopen this until I've investigated things a bit more, this is an issue that should be fixed.

**Comment by marcpabst** [comment] 2024-02-13 18:08
Just to add some context, using `objc` I can get the first column of the matrix by "lying" and telling `msg_send!` I'm expecting a `[f32, 4]` array (or something memory-equivalent). But when I tell `msg_send!` I want a `[f32, 16]`, it all breaks and all values are off.

**Comment by madsmtm** [comment] 2024-02-13 22:56
From my reading of Clang's source code, the ABI expects us to use `objc_msgSend` and not `objc_msgSend_stret` in the following cases:
- On ARM, 128bit types with the `AAPCS16_VFP` ABI (maybe some kind of floating point vectors?).
- On x86 Darwin, 128bit vectors.
- On x86_64, 256bit and 512bit vectors. Also unaligned structures are forced in `objc_msgSend_stret`?
- Aarch64 is heaven, there's only ever `objc_msgSend`.

Though the code is quite involved, and I glossed over a lot of the details.

But it does seem like vector types at the very least need some sort of different handling to have the correct message-sending ABI. I don't know how vector types relate to SIMD, but they sound similar, so maybe SIMD types do also use a different ABI?

**Comment by marcpabst** [comment] 2024-02-14 14:23
Yep, that's what I saw as well.  I'm on `aarch64` (iPad/MacBook Pro M2), so `objc_msgSend` should be the way to go, Does `msg_send!` default to `objc_msgSend_stret`?

**Comment by madsmtm** [comment] 2024-02-14 15:56
`msg_send!` picks the right message sending function based on the return type, see:
https://github.com/madsmtm/objc2/blob/155edc19bb3f1f3851679b277ad321cda4db365a/crates/objc2/src/runtime/message_receiver.rs#L53-L154

But I think this logic is subtly wrong for vector types, and that's what I want to fix.

All of this is only tangentially related to your problem of not being able to implement `Encode` correctly, and then panicking, that part _should_ be fairly easy to solve.

**Comment by marcpabst** [comment] 2024-02-14 16:14
But I tried with the `objc` crate that I assume used the same or simmiliar logics (but lacks the verification of encodings by default) - I presume this might be related to the way structs are handled?

**Comment by madsmtm** [comment] 2024-02-15 03:35
I actually suspect the code example you provided might technically be wrong too on Aarch64, as the ABI of SIMD types isn't the same as the ABI of a C struct - it happens to work since you use the large `simd_float4x4`, but passing a type like `simd_float4` across an ABI boundary requires you to use the corresponding `Simd<f32, 4>` / `core::arch::aarch64::float32x4_t`.

In general, I'm unsure of the state of SIMD FFI support? There's [`feature(simd_ffi)`](https://github.com/rust-lang/rust/issues/63068), but that hasn't gotten far.

**Comment by madsmtm** [comment] 2024-02-15 04:05
Re examples: There are some in [`objc2::encode`](https://docs.rs/objc2/0.5.0/objc2/encode/index.html), but is there another place where it would have been more visible / more easily understandable?

**Comment by marcpabst** [comment] 2024-02-16 15:10
I think the examples are quite good already, but as some point it might be worth to add a short user guide / getting started page and then link to the examples.

**Closed** 2024-05-10 00:05 UTC
Labels: bug, A-objc2

**Comment by madsmtm** [comment] 2024-05-10 00:07
I've added `Encoding::None` in https://github.com/madsmtm/objc2/pull/584 to allow you to specify when Clang doesn't emit an encoding for a type, no timeline on a release.

Note that this does not mean that `objc2` officially supports SIMD types; the wrong message-sending function may still be chosen, and Rust's own support for it is yet lacking.

**Comment by marcpabst** [comment] 2024-05-10 09:37
Great, thank you! I haven't looked into this for a while but will definitely come back to this shortly for an ongoing project.

**Comment by marcpabst** [comment] 2024-05-28 18:10
Returning to this, before I give it another shot - do you think accessing SIMD vectors will now work?

> Note that this does not mean that objc2 officially supports SIMD types; the wrong message-sending function may still be chosen, and Rust’s own support for it is yet lacking.

Not entirely sure how to interpret this - does this mean that we still need upstream support, or is there a chance it might just work?

**Comment by madsmtm** [comment] 2024-05-28 18:15
I think you can try it out with the new encoding, might be that you're lucky, and that you can get the specific methods to work that you need - though I will still warn that it's fully undefined behaviour until we get support for SIMD in FFI in Rust (the [`simd_ffi`](https://github.com/rust-lang/rust/issues/63068) feature that I linked earlier) (I suspect the issue is [the same as it was with `i128`](https://blog.rust-lang.org/2024/03/30/i128-layout-update.html), Rust / Clang / GCC don't agree on the C ABI for these).
