### ISSUE TITLE
Failure to compile on Rust nightly 1.70.0

### ISSUE THREAD

**Issue by janhohenheim** [madsmtm/objc2#432] opened 2023-03-20 14:13 UTC
I'm not using this crate at all, but it is a transient dependency of mine and I recently got a CI failure.
It seems like `objc2-0.3.0-beta.3.patch-leaks.2` [fails to compile on Rust nightly 1.70.0](https://github.com/janhohenheim/foxtrot/actions/runs/4463874536/jobs/7839504250?pr=240), but [compiles on nightly 1.69.0](https://github.com/janhohenheim/foxtrot/actions/runs/4469299962/jobs/7851208967).

**Comment by madsmtm** [comment] 2023-03-20 18:09
Thank you for the report! I've verified that it is present on `master` as well.

It seems more like a `std` or `rustc` bug though? The bounds on our `Iterator` impl should be completely fine, but it now fails due to the `Self::Item: ~const Destruct` bound on `fn nth` added in https://github.com/rust-lang/rust/pull/104100.

I'll probably submit a regression report upstream in the next few days (if you don't do it first?).

**Comment by janhohenheim** [comment] 2023-03-20 18:47
Since you actually know about the soundness of your code, I'd be glad if you could submit it 🙂

**Comment by fee1-dead** [comment] 2023-03-21 05:03
I'm not sure if the `~const Destruct` bound is the culprit, since it should have no effect on code that are not using const trait bounds.

**Comment by kchibisov** [comment] 2023-03-26 15:13
@fee1-dead be aware that the main issue here that it's a regression from stable to nightly since the latest stable builds this code just fine.

I could submit bug report as well though, but I'm not a maintainer of this crate, and not sure I can clearly express the issue other than saying that code was fine on stable for like near a year.

**Comment by fee1-dead** [comment] 2023-03-26 15:21
I wasn't denying that the regression exists. I was mainly coming from a rustc maintainer perspective since I approved the linked PR above. To find the actual change that caused this would involve cargo-bisect-rustc. I don't have time to run that right now, but opening a rust-lang/rust issue would help as well.

**Comment by kchibisov** [comment] 2023-03-26 15:32
Opened upstream ticket https://github.com/rust-lang/rust/issues/109632

**Comment by madsmtm** [comment] 2023-03-26 18:31
I'd like to wait and see what happens upstream, since it _is_ a `rustc` bug, but if the issue persists for let's say ~5 days more, I'll push a patched `objc2` version to deal with it regardless

**Comment by madsmtm** [comment] 2023-04-02 14:41
Update: I've [created a new version `0.3.0-beta.3.patch-leaks.3`](https://github.com/madsmtm/objc2/releases/tag/objc-0.3.0-beta.3.patch-leaks.3), so affected `nightly` users should simply be able to do a `cargo update` to fix the issue in the meantime.

@fee1-dead created https://github.com/rust-lang/rust/pull/109684, so I suspect that the issue will be fixed properly soon - I will keep this issue open until that happens.

**Comment by madsmtm** [comment] 2023-04-13 17:40
This has been fixed upstream now, thanks to @fee1-dead for their work in doing so!

**Closed by madsmtm** 2023-04-13 17:40 UTC
Labels: bug
